version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: cargo
    directory: /analytics/ffi
    schedule:
      interval: weekly
  - package-ecosystem: pip
    directory: /analytics
    schedule:
      interval: weekly
